language: go
sudo: false
go:
  - 1.7
  - 1.8
  - tip
go_import_path: github.com/drkaka/lg
env:
  global:
    - GO15VENDOREXPERIMENT=1
    - TEST_TIMEOUT_SCALE=10
cache:
  directories:
    - vendor
install:
  - echo "Installing Glide and locked dependencies..."
	- glide --version || go get -u -f github.com/Masterminds/glide
	- glide install
	- echo "Installing test dependencies..."
	- go install ./vendor/github.com/mattn/goveralls
script:
  - go test -race -v ./...
after_success:
  - goveralls -service=travis-ci